// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: remote_actor.proto

package remote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteActor_Tell_FullMethodName = "/remote.RemoteActor/Tell"
	RemoteActor_Ask_FullMethodName  = "/remote.RemoteActor/Ask"
	RemoteActor_Stop_FullMethodName = "/remote.RemoteActor/Stop"
)

// RemoteActorClient is the client API for RemoteActor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RemoteActor service allows transparent remote actor communication.
type RemoteActorClient interface {
	// Tell sends a fire-and-forget message to a remote actor.
	Tell(ctx context.Context, in *TellRequest, opts ...grpc.CallOption) (*TellResponse, error)
	// Ask sends a message and waits for a reply (with server-side timeout).
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
	// Stop gracefully stops a remote actor.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type remoteActorClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteActorClient(cc grpc.ClientConnInterface) RemoteActorClient {
	return &remoteActorClient{cc}
}

func (c *remoteActorClient) Tell(ctx context.Context, in *TellRequest, opts ...grpc.CallOption) (*TellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TellResponse)
	err := c.cc.Invoke(ctx, RemoteActor_Tell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteActorClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, RemoteActor_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteActorClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, RemoteActor_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteActorServer is the server API for RemoteActor service.
// All implementations must embed UnimplementedRemoteActorServer
// for forward compatibility.
//
// RemoteActor service allows transparent remote actor communication.
type RemoteActorServer interface {
	// Tell sends a fire-and-forget message to a remote actor.
	Tell(context.Context, *TellRequest) (*TellResponse, error)
	// Ask sends a message and waits for a reply (with server-side timeout).
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	// Stop gracefully stops a remote actor.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedRemoteActorServer()
}

// UnimplementedRemoteActorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteActorServer struct{}

func (UnimplementedRemoteActorServer) Tell(context.Context, *TellRequest) (*TellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tell not implemented")
}
func (UnimplementedRemoteActorServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedRemoteActorServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedRemoteActorServer) mustEmbedUnimplementedRemoteActorServer() {}
func (UnimplementedRemoteActorServer) testEmbeddedByValue()                     {}

// UnsafeRemoteActorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteActorServer will
// result in compilation errors.
type UnsafeRemoteActorServer interface {
	mustEmbedUnimplementedRemoteActorServer()
}

func RegisterRemoteActorServer(s grpc.ServiceRegistrar, srv RemoteActorServer) {
	// If the following call panics, it indicates UnimplementedRemoteActorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteActor_ServiceDesc, srv)
}

func _RemoteActor_Tell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteActorServer).Tell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteActor_Tell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteActorServer).Tell(ctx, req.(*TellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteActor_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteActorServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteActor_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteActorServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteActor_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteActorServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteActor_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteActorServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteActor_ServiceDesc is the grpc.ServiceDesc for RemoteActor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteActor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote.RemoteActor",
	HandlerType: (*RemoteActorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tell",
			Handler:    _RemoteActor_Tell_Handler,
		},
		{
			MethodName: "Ask",
			Handler:    _RemoteActor_Ask_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _RemoteActor_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote_actor.proto",
}
