// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: remote_actor.proto

package remote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TellRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorId        string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	MsgType        string                 `protobuf:"bytes,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	PayloadJson    []byte                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON-encoded payload
	PayloadType    string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"` // fully-qualified Go type name for deserialisation
	Sender         string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	TimestampNanos int64                  `protobuf:"varint,6,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"` // Unix nanosecond timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TellRequest) Reset() {
	*x = TellRequest{}
	mi := &file_remote_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellRequest) ProtoMessage() {}

func (x *TellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellRequest.ProtoReflect.Descriptor instead.
func (*TellRequest) Descriptor() ([]byte, []int) {
	return file_remote_actor_proto_rawDescGZIP(), []int{0}
}

func (x *TellRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *TellRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *TellRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *TellRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *TellRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TellRequest) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

type TellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TellResponse) Reset() {
	*x = TellResponse{}
	mi := &file_remote_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TellResponse) ProtoMessage() {}

func (x *TellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TellResponse.ProtoReflect.Descriptor instead.
func (*TellResponse) Descriptor() ([]byte, []int) {
	return file_remote_actor_proto_rawDescGZIP(), []int{1}
}

type AskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActorId        string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	MsgType        string                 `protobuf:"bytes,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	PayloadJson    []byte                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	PayloadType    string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Sender         string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	TimestampNanos int64                  `protobuf:"varint,6,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	TimeoutMs      int64                  `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // server-side timeout for Ask
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_remote_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_remote_actor_proto_rawDescGZIP(), []int{2}
}

func (x *AskRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AskRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *AskRequest) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *AskRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *AskRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *AskRequest) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

func (x *AskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	PayloadType   string                 `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_remote_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_remote_actor_proto_rawDescGZIP(), []int{3}
}

func (x *AskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AskResponse) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *AskResponse) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *AskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_remote_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_remote_actor_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_remote_actor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_actor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_remote_actor_proto_rawDescGZIP(), []int{5}
}

var File_remote_actor_proto protoreflect.FileDescriptor

const file_remote_actor_proto_rawDesc = "" +
	"\n" +
	"\x12remote_actor.proto\x12\x06remote\"\xca\x01\n" +
	"\vTellRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\tR\amsgType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12'\n" +
	"\x0ftimestamp_nanos\x18\x06 \x01(\x03R\x0etimestampNanos\"\x0e\n" +
	"\fTellResponse\"\xe8\x01\n" +
	"\n" +
	"AskRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\tR\amsgType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12'\n" +
	"\x0ftimestamp_nanos\x18\x06 \x01(\x03R\x0etimestampNanos\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x03R\ttimeoutMs\"\x83\x01\n" +
	"\vAskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\tR\vpayloadType\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"(\n" +
	"\vStopRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\"\x0e\n" +
	"\fStopResponse2\xa3\x01\n" +
	"\vRemoteActor\x121\n" +
	"\x04Tell\x12\x13.remote.TellRequest\x1a\x14.remote.TellResponse\x12.\n" +
	"\x03Ask\x12\x12.remote.AskRequest\x1a\x13.remote.AskResponse\x121\n" +
	"\x04Stop\x12\x13.remote.StopRequest\x1a\x14.remote.StopResponseB5Z3github.com/LukaKeselj/Agenti/actor-framework/remoteb\x06proto3"

var (
	file_remote_actor_proto_rawDescOnce sync.Once
	file_remote_actor_proto_rawDescData []byte
)

func file_remote_actor_proto_rawDescGZIP() []byte {
	file_remote_actor_proto_rawDescOnce.Do(func() {
		file_remote_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_actor_proto_rawDesc), len(file_remote_actor_proto_rawDesc)))
	})
	return file_remote_actor_proto_rawDescData
}

var file_remote_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_remote_actor_proto_goTypes = []any{
	(*TellRequest)(nil),  // 0: remote.TellRequest
	(*TellResponse)(nil), // 1: remote.TellResponse
	(*AskRequest)(nil),   // 2: remote.AskRequest
	(*AskResponse)(nil),  // 3: remote.AskResponse
	(*StopRequest)(nil),  // 4: remote.StopRequest
	(*StopResponse)(nil), // 5: remote.StopResponse
}
var file_remote_actor_proto_depIdxs = []int32{
	0, // 0: remote.RemoteActor.Tell:input_type -> remote.TellRequest
	2, // 1: remote.RemoteActor.Ask:input_type -> remote.AskRequest
	4, // 2: remote.RemoteActor.Stop:input_type -> remote.StopRequest
	1, // 3: remote.RemoteActor.Tell:output_type -> remote.TellResponse
	3, // 4: remote.RemoteActor.Ask:output_type -> remote.AskResponse
	5, // 5: remote.RemoteActor.Stop:output_type -> remote.StopResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remote_actor_proto_init() }
func file_remote_actor_proto_init() {
	if File_remote_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_actor_proto_rawDesc), len(file_remote_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_actor_proto_goTypes,
		DependencyIndexes: file_remote_actor_proto_depIdxs,
		MessageInfos:      file_remote_actor_proto_msgTypes,
	}.Build()
	File_remote_actor_proto = out.File
	file_remote_actor_proto_goTypes = nil
	file_remote_actor_proto_depIdxs = nil
}
